### ISSUE TITLE
Supported types are incorrect for icon parameter

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js-docs-reference#1041]
For the _icon_ property, it says:

> It is only applicable if the type is InformationalMessage. Specifying this parameter for an unsupported type results in an exception.

However, this parameter is required if the _type_ property is set to **Office.MailboxEnums.ItemNotificationMessageType.InsightMessage**.  Otherwise, the following error is thrown if the icon parameter is not provided with the _insightMessage_ type:

````
Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null.
Parameter name: icon
    at L (https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:242419)
    at q (https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:242836)
    at jt (https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:269657)
    at https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:270443
    at Ht (https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:271260)
    at Object.Bt (https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:271657)
    at showInfoBar (https://localhost:3000/src/commands/commands.js:41:52)
    at Object.onMessageComposeHandler [as callback] (https://localhost:3000/src/commands/commands.js:6:3)
    at https://appsforoffice.microsoft.com/lib/beta/hosted/outlook-web-16.01.js:20:175690
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7047828-a297-b6eb-bd50-6a9b6fd14eb4
* Version Independent ID: 836d1b89-3600-069f-6acd-373807bd96a8
* Content: [Office.NotificationMessageDetails interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessagedetails?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.notificationmessagedetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.notificationmessagedetails.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @elegault,
Thanks for pointing this out. @ElizabethSamuel-MSFT, could you please investigate and make the appropriate documentation changes?

**Comment by ElizabethSamuel-MSFT** [comment]
@elegault The docs have now been updated. Do let us know if you face any further issues.

Thanks!
