### ISSUE TITLE
Simple space regex won't work when regional setting is "Germany"

### ISSUE THREAD

**Issue by abhinovpankaj** [OfficeDev/office-js-docs-reference#1321]
I am using word API to create  a simple Word Add-in for find and replace function.

Regional settings: US
The below code like charm, and it searches just fine.
`async function wildcardSearch() {
  await Word.run(async (context) => {
    // Check out how wildcard expression are built, also use the second parameter of the search method to include search modes
    // (i.e. use wildcards).
    let results = context.document.body.search(" {2,}", { matchWildcards: true,  });
    results.load("length");

    await context.sync();}`

Once the regional settings changes to attached image, simple search starts to throw exception.
![image](https://user-images.githubusercontent.com/15319976/178551878-e652ff60-3147-458a-9f64-bf78ce56eb04.png)

Exception :

[ERROR]: Error:
{
    "stack": "RichApi.Error: GeneralException\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:244488)\n    at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:308654)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:306717",
    "message": "GeneralException",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "GeneralException",
        "errorLocation": "",
        "statement": "_Search2.load([\"length\"]);",
        "surroundingStatements": [
            "var root = context.root;",
            "var body = root.body;",
            "// Instantiate {body}",
            "var _Search2 = body._Search2(...);",
            "// Instantiate {_Search2}",
            "// >>>>>",
            "_Search2.load([\"length\"]);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}

**Comment by AlexJerabek** [comment]
Hi @abhinovpankaj,

Thanks for reporting this issue. This appears to be a product bug, so I'll transfer this issue to the office-js repo. There, members of the product team can investigate your findings.
