### ISSUE TITLE
Load + Sync + Access on ContentControl, Range, or Paragraph Leads to Race Condition At Scale

### ISSUE THREAD

**Issue by cScarlson** [OfficeDev/office-js-docs-reference#801]
## Issue
The documentation seems to have a caveat to the "_must invoke context.sync()_ method". I am encountering a **Race Condition** when performing `paragraphs.load('items')` **at scale**. Performing operations within a Promise-Pipeline works fine for a single `paragraphs.load('items')` + `context.sync()` + `paragraphs.items` routine.

### Intention
I have to keep track of numerous ContentControls alongside their associations, so I set up a pipeline to map to a `Promise<IClauseControlSet>`.

```typescript
var pMapped = loadBalanceMap(controls).then( mapped => console.log('MAPPED', mapped) );
```

```typescript
interface IClauseControlSet {
  tag: string;
  control: Word.ContentControl;
  range: Word.Range;
  paragraphs: Word.Paragraph[];   // reflective of range.paragraphs.items[n]
  entries: string[];              // reflective of range.paragraphs.items[n].text
  text: string;
}
```

```typescript
    function loadBalanceMap(controls: Word.ContentControl[]) {
      return new Promise((resolve, reject) => {  // MS Word JS API has foundational Race Conditions when calling .load(x) & .sync() in rapid succession
        var mapped = [ ];
        
        // for (let i = 0, len = controls.length; i < len; i++) setTimeout( () => director.populate(controls[i]).then( data => mapped.push(data) ).then(check), 0 );  // push to Event Loop
        for (let i = 0, len = controls.length; i < len; i++) director.populate(controls[i]).then( data => mapped.push(data) );  // !ATTENTION! This will throw an error!
        
        function check() {
          console.log('POP!...', mapped.length === controls.length);
          if ( mapped.length !== controls.length ) return;
          console.log('...DING!', mapped.length === controls.length);
          return Promise.all(mapped).then( all => resolve(all) );
        }
        
      });
    }
```

Notice the uncommented `for` loop within `loadBalanceMap()`. This will throw:

```
zone.js:391 Uncaught (in promise) RichApi.Error: The property 'items' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.
    at new n (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-web-16.00.js:26:294903)
    at Function.n.createPropertyNotLoadedException (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-web-16.00.js:26:392930)
    at n.throwIfNotLoaded (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-web-16.00.js:26:392835)
    at n.get [as items] (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-web-16.00.js:26:643306)
    at https://localhost:3000/taskpane.js:128382:86
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (https://localhost:3000/taskpane.js:124805:26)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.run (https://localhost:3000/taskpane.js:124564:43)
    at https://localhost:3000/taskpane.js:125303:34
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://localhost:3000/taskpane.js:124837:31)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.runTask (https://localhost:3000/taskpane.js:124609:47)
```

However, commenting that line out and uncommenting the special version using `setTimeout` works just fine (albeit heinous). Note that **I _should_ be able to simply write** `var pMapped = controls.map( control = director.populate(controls[i]) );`. Now I have a disgusting looking function that specializes in something that should be a one-liner.

## Synopsis
It seems that "you must call `context.sync()`" is not _mandatory_ as much as it provides you with better _luck_ -- as long as you perform such on a single datum _only_. Otherwise, **there is still a Race Condition somewhere in this part of the framework's foundation**.

###### `package.json`
```json
{
  ...
  "dependencies": {
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@ckeditor/ckeditor5-angular": "^1.2.3",
    "@ckeditor/ckeditor5-build-classic": "^22.0.0",
    "@microsoft/office-js-helpers": "^1.0.1",
    "office-ui-fabric-js": "^1.3.0",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular/cli": "^10.1.1",
    "@babel/core": "^7.11.6",
    "@babel/polyfill": "^7.11.5",
    "@babel/preset-env": "^7.11.5",
    "@types/find-process": "1.2.0",
    "@types/office-js": "^1.0.128",
    "@types/office-runtime": "^1.0.17",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.1.2",
    "core-js": "^3.6.5",
    "eslint-config-office-addins": "^1.0.17",
    "file-loader": "^4.3.0",
    "find-process": "^1.4.3",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^4.4.1",
    "node-sass": "^4.14.1",
    "office-addin-cli": "^1.0.12",
    "office-addin-debugging": "^3.0.33",
    "office-addin-dev-certs": "^1.5.4",
    "office-addin-lint": "^1.0.25",
    "office-addin-manifest": "1.5.0",
    "office-addin-prettier-config": "^1.0.13",
    "raw-loader": "^4.0.1",
    "sass-loader": "^10.0.2",
    "source-map-loader": "^0.2.4",
    "ts-loader": "^6.2.2",
    "typescript": "^3.9.7",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  },
  "prettier": "office-addin-prettier-config"
}
```

**Comment by Rick-Kirkham** [comment]
I suspect is is more of a product bug issue than a documentation issue, but I will hold off transferring it to the office-js repo for now. In the meantime, I cannot tell from the code you provided where you are calling `.load` and `context.sync`. Could you provide that? Also, be sure that you are not calling `context.sync` inside a loop (which includes the `map` function). See [Avoid using the context.sync method in loops](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/correlated-objects-pattern).
